In [11]:
import json
data = []
for i in range(2):
    with open(f"darija_worker{i}.jsonl","r",encoding='utf-8') as file:
        for line in file:
            # Parse each line as a JSON object
            json_object = json.loads(line.strip())
            data.append(json_object)
len(data)

87060

In [12]:
import pandas as pd
df = pd.DataFrame(data)
df.head()

   id              en                 fr         darija
0   0    The Wanderer  Le grand Meaulnes     اللي كيدور
1   1  Alain-Fournier     Alain-Fournier   ألان فورنييه
2   2      First Part    PREMIÈRE PARTIE    الجزء الأول
3   3               I   CHAPITRE PREMIER            أنا
4   4     THE BOARDER    LE PENSIONNAIRE  اللي كاري بيت

In [17]:
df.duplicated(subset="id").sum()

np.int64(5)

In [19]:
from datasets import load_dataset
ds = load_dataset("Helsinki-NLP/opus_books", "en-fr", split="train")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [25]:
ids_list = df["id"].to_list()
filtred_ds = ds.filter(
    lambda x: int(x["id"]) in ids_list
)
filtred_ds

Filter:   0%|          | 0/127085 [00:00<?, ? examples/s]

Dataset({
    features: ['id', 'translation'],
    num_rows: 87055
})

In [32]:
filtred_ds_list = []
for row in filtred_ds:
    row["translation"]["id"] = int(row["id"])
    filtred_ds_list.append(
        row["translation"]
    )

In [33]:
ds_df = pd.DataFrame(filtred_ds_list)
ds_df.head()

               en                 fr  id
0    The Wanderer  Le grand Meaulnes   0
1  Alain-Fournier     Alain-Fournier   1
2      First Part    PREMIÈRE PARTIE   2
3               I   CHAPITRE PREMIER   3
4     THE BOARDER    LE PENSIONNAIRE   4

In [38]:
result = pd.merge(ds_df, df[["id","darija"]], on='id')
result.head()

               en                 fr  id         darija
0    The Wanderer  Le grand Meaulnes   0     اللي كيدور
1  Alain-Fournier     Alain-Fournier   1   ألان فورنييه
2      First Part    PREMIÈRE PARTIE   2    الجزء الأول
3               I   CHAPITRE PREMIER   3            أنا
4     THE BOARDER    LE PENSIONNAIRE   4  اللي كاري بيت

In [42]:
result.sample(13)

                                                      en  ...                                             darija
43633  There was one hanging up in a hotel at Oxford ...  ...  كان واحد معلق فواحد لوطيل فـأكسفورد كنت ساكن ف...
67841  One day, carried off by a hurricane from neigh...  ...  واحد النهار، جاب إعصار من الشواطئ اللي حداها ش...
70649  But ultimately I feel less sorry for them than...  ...  "ولكن في الأخير، كنحس بالأسف على آلاف الناس ال...
4910   Miss Lucas perceived him from an upper window ...  ...  آنسة لوكاس شافتو من واحد الشرجم الفوقاني وهو غ...
84648  Chapter IX IN WHICH THE RED SEA AND THE INDIAN...  ...  الفصل التاسع: اللي فيه البحر الأحمر والمحيط ال...
65324  To cast off, he needed only to fire and stoke ...  ...     باش يقلع، كان خاصو غير يشعل العافية فالفورنات!
21342  We sent for this guide, who told us he would u...  ...  عيطنا لهاد الدليل، وقال لينا بلي يقدر يدينا من...
75386      Half an hour later they arrived at the river.  ...                       نص ساعة من بعد، وصلوا للواد.
23079  L’un, a la figure longue et pale, se tenait re...  ...  واحد فيهم، وجهو طويل وشاحب، كان متكي فكرسي كيت...
20990  He answered in Latin, Christianus; but was so ...  ...  جاوبني باللاتينية، "كريستيانو" (مسيحي)؛ ولكن ك...
60057  As Saint-Giraud kept on repeating that it was ...  ...  فاش بقى سان جيرو كيعاود بلي مستحيل الواحد يعيش...
12455     "Then, Jane, you must play the accompaniment."  ...                    "إذن يا جين، خاصك تعزفي معايا."
57491  'I thought as much,' he told himself bitterly,...  ...  "كنت عارفها،" قال لراسو بمرارة، "الحب ديالها غ...

[13 rows x 4 columns]